// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDgD3EKvSLQB5G7K-uKtm59dSDH6milg6A',
    appId: '1:660689092148:web:ae48d61aeb00f7e7659461',
    messagingSenderId: '660689092148',
    projectId: 'marketapp-dev-555',
    authDomain: 'marketapp-dev-555.firebaseapp.com',
    storageBucket: 'marketapp-dev-555.firebasestorage.app',
    measurementId: 'G-QDWBXGWJDR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAFGq9-18bOa7hZ57Bdg5eUvFINZsfv3BA',
    appId: '1:660689092148:android:f1c3efe3fc92c5c2659461',
    messagingSenderId: '660689092148',
    projectId: 'marketapp-dev-555',
    storageBucket: 'marketapp-dev-555.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA9H0Q06BV1UCiyCs6kGG0UpvPh-9mzmjQ',
    appId: '1:660689092148:ios:da2c13165908ac45659461',
    messagingSenderId: '660689092148',
    projectId: 'marketapp-dev-555',
    storageBucket: 'marketapp-dev-555.firebasestorage.app',
    iosBundleId: 'com.example.marketApp',
  );
}
